repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        # additional_dependencies: [flake8-docstrings]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.761"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --disallow-untyped-defs]
        exclude: "(test_*)|(setup.py)"
